### ISSUE TITLE
Bot ignores commands where it is mentioned

### ISSUE THREAD

**Issue by felurx** [TheWildBear/bigDataTelgrambot#11]
Situation:
User types in /, Telegram suggests commands. User taps on command (or holds command for adding args), User sends command like this: /<cmd>@<username> (<args>)

Expected behaviour:
Bot processes the command like if there is no username

Actual behaviour:
Bot ignores command, nothing happens

**Comment by TheWildBear** [comment]
in which command does this happen? In my test's it didn't happen...
Did you make sure, that you didn't just do the /count command without args?

**Comment by TheWildBear** [comment]
As Tests showed that is only the case when using commands that require user input

**Comment by TheWildBear** [comment]
Fixed with: 4da680649b6f510be2a3ba1bd8999d931b355d7b
