### ISSUE TITLE
SQL Injection crashes bot

### ISSUE THREAD

**Issue by SitiSchu** [TheWildBear/bigDataTelgrambot#2]
![image](https://user-images.githubusercontent.com/18517178/34182008-d96768b4-e514-11e7-8740-9f81670a7e12.png)
`/count ';SELECT * FROM messages;`
After running the above command the bot died and didn't respond anymore

**Comment by Bergiu** [comment]
I think this is a duplicate of #1. Hope this will be fixed soon

**Comment by TheWildBear** [comment]
that issue is from telegram because the string ends earlier than it should... this crashes the bot... ill look for an workaround
