### ISSUE TITLE
Issue from Niklas

### ISSUE THREAD

**Issue by geozukunft** [TheWildBear/bigDataTelgrambot#20]
"Boah ey mach des man bei /count sieht wie viele der messages commands beinhalten, vielleicht auch andere entities wenn man schon dabei ist CIAO ICH BIN RAUS"
Oh wenn du eh n Issue machst, dann mach gleich noch eins mit "Boah eyy, wir brauchen /count_regexp (oder ähnliches) damit man auf das REGEXP von MySQL nutzen kann und nicht nur LIKE"
oder man macht Regex als default und macht /count_like für wenns schnell gehen muss
egal, hauptsache regex schwör
dann macht man halt ne regex whitelist oder limited die Zeit die n Query brauchen darf oder so

The issue to be read here: https://t.me/TheVillageDev/52261

**Comment by TheWildBear** [comment]
Fixed in c6614e6
