### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by geozukunft** [TheWildBear/bigDataTelgrambot#26]
make commands only available to admins and users that are opt-in

**Comment by TheWildBear** [comment]
in my opinion that should not be the case. Because users not willing to give their data could not use the service anymore but their data is not needed for the command they wanted to execute...
Why do you think, that that behavior should be used @geozukunft ?

**Comment by geozukunft** [comment]
As far as I remember there was some talk about that in a chat. So I wrote it down. It is not necessary to block them but they could get the data provided by other people without contributing to the project.

**Comment by TheWildBear** [comment]
In my opinion this would be wrong and as such should not be added!
