### ISSUE TITLE
top command spams chat

### ISSUE THREAD

**Issue by TheWildBear** [TheWildBear/bigDataTelgrambot#6]
the top command spams the chat, maybe add a feature to modify one message
Request from @shenef

**Comment by geozukunft** [comment]
Isn't this issue already solved?

**Comment by TheWildBear** [comment]
@geozukunft
Unfortunately it is not yet :pensive:
Still have to come up with a good way to do that. One that is good to use but not spammy....

**Comment by TheWildBear** [comment]
For now this is (i quess) solved with a countdown which deletes the message automatically after a set amount of time...
Is this solution okay for you @shenef?

**Comment by TheWildBear** [comment]
Closed after speaking with @shenef about it
